### ISSUE TITLE
Error under lambda_config

### ISSUE THREAD

**Issue by cbarattini** [PacoVK/terraform-aws-functionbeat#2]
Hi, I'm attempting to test this module and am running into an error each time I attempt terraform apply. 
![Screen Shot 2022-07-15 at 1 32 42 PM](https://user-images.githubusercontent.com/41753876/179306337-f5fc295d-dcad-408c-a8d6-8eb7cbd69b32.png)

Any help would be great

**Comment by PacoVK** [comment]
Hey @cbarattini please share a bit more context. The error message says you are passing a wrong data structure into the module. It has to be valid HCL. You can read more about the correct usage [here](https://faun.pub/terraform-functionbeat-e481554d729e)

**Comment by cbarattini** [comment]
Hi Paco,  I was able to figure it out, just specified default. But I'm running into another issue after attempting apply:
<img width="621" alt="Screen Shot 2022-07-20 at 1 45 45 PM" src="https://user-images.githubusercontent.com/41753876/180095395-7ab6bed9-9138-4849-a549-d78a418213f6.png">

**Comment by PacoVK** [comment]
Hey great you figured out, unfortunately this is obviously an issue with your local (windows) environment. Nothing related to this module and not something i can help you out. Hence closing this issue.
